FROM node:lts-slim

WORKDIR /app/server

RUN apt-get update -y && apt-get install -y openssl

COPY package*.json ./
COPY ./prisma ./prisma/
COPY tsconfig.json .

RUN npm install
RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3300

CMD ["sh", "-c", "npx prisma migrate deploy && node dist/seed.js --import && node dist/server.js"]